labels: &labels
  - 'dependencies'
  - 'dependabot'

schedule: &schedule
  interval: weekly

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: *schedule
    labels: *labels

  - package-ecosystem: github-actions
    directory: /
    schedule: *schedule
    labels: *labels
