version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'dependencies'
      - 'dependabot'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'dependencies'
      - 'dependabot'
