name: CD

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run: python --version
      - name: pip version
        run: pip --version
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
          sam --version
