name: CD

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Homebrew
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - name: Test Homebrew
        run: /home/linuxbrew/.linuxbrew/bin/brew --version
      - name: Homebrew tap AWS
        run: /home/linuxbrew/.linuxbrew/bin/brew tap aws/tap
