name: CD

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Homebrew and AWS SAM CLI
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew tap aws/tap
          /home/linuxbrew/.linuxbrew/bin/brew install aws-sam-cli
      - name: LS SAM
        run: ls /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/
      - name: LS SELF
        run: ls -la
      #- name: SAM build
      #run: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/bin/sam build
