name: Main

on:
  push:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/aws-sam/
        with:
          command: npm run build
